import React,{useEffect,useState,useRef} from "react";
import {SUDOKU,NOME,QUIZ,SICURA,INSICURA,PACCO,DOPPIO_FONDO,SOL,PUZ} from "./dati.js";
const C={carta:"#d8c18d",chiara:"#f1e4bc",ink:"#171813",rosso:"#8b271f",oro:"#b58b3b",tenue:"#6f6756",dark:"#11120f"};
const mono="ui-monospace,SFMono-Regular,Menlo,monospace",serif="Georgia,serif";
const ZIP_IMG="https://ama-stay.com/imager/uploads/Summer/3739/zipline-san-vigilio_2654fe719bdc554d201821f3404c6e84_573d1886ddff61a5fa23e4ee8ca84447.jpg";
function Btn({children,onClick,disabled=false,alt=false}){return <button disabled={disabled} onClick={onClick} style={{width:"100%",padding:"16px 18px",border:`1px solid ${alt?C.oro:C.ink}`,background:alt?"transparent":C.ink,color:alt?C.ink:C.chiara,fontFamily:mono,fontWeight:900,letterSpacing:2,cursor:"pointer",opacity:disabled?.45:1,textTransform:"uppercase"}}>{children}</button>}
function TestBtn({onClick,children}){return <button onClick={onClick} style={{width:"100%",padding:"11px 14px",border:`1px dashed ${C.rosso}`,background:"rgba(139,39,31,.06)",color:C.rosso,fontFamily:mono,fontWeight:900,letterSpacing:1.4,cursor:"pointer",marginTop:10,fontSize:11}}>{children}</button>}
function Card({children,label="PRATICA ATTIVA"}){return <section style={{background:C.chiara,border:`1px solid rgba(23,24,19,.75)`,boxShadow:"0 18px 45px rgba(0,0,0,.22)",marginBottom:22,overflow:"hidden"}}><div style={{padding:"10px 14px",background:C.ink,color:C.carta,fontFamily:mono,fontSize:9,letterSpacing:1.6,display:"flex",justifyContent:"space-between"}}><span>FASCICOLO 08/26</span><span>{label}</span></div><div style={{padding:22}}>{children}</div></section>}
function Head({eye,title}){return <><div style={{fontFamily:mono,fontSize:11,letterSpacing:2,color:C.rosso,fontWeight:900}}>{eye}</div><h1 style={{fontFamily:serif,fontSize:30,lineHeight:1.05,whiteSpace:"pre-line",margin:"10px 0 18px"}}>{title}</h1></>}
function Text({children}){return <div style={{fontFamily:serif,fontSize:17,lineHeight:1.55,whiteSpace:"pre-line",marginBottom:20}}>{children}</div>}
function Stamp({children}){return <div style={{display:"inline-block",border:`2px solid ${C.rosso}`,color:C.rosso,fontFamily:mono,fontWeight:900,padding:"6px 9px",transform:"rotate(-3deg)",letterSpacing:1.5,fontSize:11,marginBottom:16}}>{children}</div>}
function ScratchCard({text,image,onDone}){const canvasRef=useRef(null),boxRef=useRef(null),drawing=useRef(false),[revealed,setRevealed]=useState(false);useEffect(()=>{const canvas=canvasRef.current,box=boxRef.current;if(!canvas||!box)return;const dpr=Math.max(1,window.devicePixelRatio||1),w=box.clientWidth,h=260;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+"px";canvas.style.height=h+"px";const ctx=canvas.getContext("2d");ctx.setTransform(dpr,0,0,dpr,0,0);const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,"#d6ad54");g.addColorStop(.5,"#b88932");g.addColorStop(1,"#8f6827");ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.fillStyle="rgba(255,255,255,.13)";for(let i=0;i<120;i++){ctx.beginPath();ctx.arc(Math.random()*w,Math.random()*h,Math.random()*2+1,0,Math.PI*2);ctx.fill()}ctx.fillStyle="#171813";ctx.textAlign="center";ctx.font=`900 20px ${mono}`;ctx.fillText("GRATTA QUI",w/2,h/2-8);ctx.font=`700 11px ${mono}`;ctx.fillText("PASSA IL DITO SULLA PATINA",w/2,h/2+22)},[]);
const scratch=e=>{const canvas=canvasRef.current;if(!canvas)return;const rect=canvas.getBoundingClientRect(),ctx=canvas.getContext("2d"),x=e.clientX-rect.left,y=e.clientY-rect.top;ctx.save();ctx.globalCompositeOperation="destination-out";ctx.beginPath();ctx.arc(x,y,31,0,Math.PI*2);ctx.fill();ctx.restore()};
const check=()=>{const canvas=canvasRef.current;if(!canvas||revealed)return;const ctx=canvas.getContext("2d"),d=ctx.getImageData(0,0,canvas.width,canvas.height).data;let transparent=0,total=0;for(let i=3;i<d.length;i+=64){total++;if(d[i]<80)transparent++}if(total&&transparent/total>.38){setRevealed(true);canvas.style.transition="opacity .45s ease";canvas.style.opacity="0";canvas.style.pointerEvents="none";setTimeout(()=>onDone?.(),250)}};
return <div><div ref={boxRef} style={{position:"relative",height:260,overflow:"hidden",border:`2px solid ${C.ink}`,marginBottom:14,background:`url(${image}) center/cover no-repeat`,display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{position:"absolute",inset:0,display:"flex",alignItems:"flex-end",justifyContent:"center",padding:20,textAlign:"center",background:"linear-gradient(0deg,rgba(0,0,0,.72),rgba(0,0,0,0) 65%)"}}><div style={{fontFamily:mono,fontWeight:900,fontSize:20,lineHeight:1.15,whiteSpace:"pre-line",color:"#fff",textShadow:"0 2px 8px rgba(0,0,0,.8)"}}>{text}</div></div><canvas ref={canvasRef} style={{position:"absolute",inset:0,touchAction:"none",cursor:"crosshair"}} onPointerDown={e=>{drawing.current=true;e.currentTarget.setPointerCapture?.(e.pointerId);scratch(e)}} onPointerMove={e=>drawing.current&&scratch(e)} onPointerUp={e=>{drawing.current=false;check();e.currentTarget.releasePointerCapture?.(e.pointerId)}} onPointerCancel={()=>{drawing.current=false;check()}} /></div><div style={{fontFamily:mono,fontSize:10,textAlign:"center",letterSpacing:1.3,color:revealed?C.rosso:C.tenue,fontWeight:revealed?900:600,marginBottom:14}}>{revealed?"CONTENUTO RIVELATO · GUARDA BENE":"GRATTA LA PATINA PER SCOPRIRE L'INDIZIO"}</div></div>}
function Opening({onOpen}){return <section style={{overflow:"hidden",background:"linear-gradient(135deg,#ead9a8,#cfb476)",border:"1px solid #5f5132",boxShadow:"0 24px 70px rgba(0,0,0,.35)"}}><div style={{padding:"14px 18px",borderBottom:"1px solid rgba(23,24,19,.45)",display:"flex",justifyContent:"space-between",fontFamily:mono,fontWeight:900,fontSize:11}}><span>FASCICOLO 08/26</span><span style={{color:C.rosso}}>CONSEGNA RISERVATA</span></div><div style={{padding:"26px 22px"}}><Stamp>RISERVATO</Stamp><div style={{fontFamily:mono,fontSize:10,letterSpacing:2,color:C.tenue,marginBottom:16}}>DESTINATARIA UNICA · ACCESSO AUTORIZZATO</div><h1 style={{fontFamily:serif,fontSize:"clamp(42px,11vw,68px)",lineHeight:.93,margin:"0 0 18px"}}>C'È UN<br/><span style={{color:C.rosso}}>REGALO</span><br/>PER LEI.</h1><p style={{fontFamily:serif,fontSize:19,lineHeight:1.5}}>Non è pubblicità. Non è uno scherzo. È una consegna personale, preparata apposta per lei.</p><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,margin:"22px 0"}}><div style={{border:`1px solid ${C.ink}`,padding:14,textAlign:"center"}}><small>SERRATURA 01</small><div style={{fontFamily:mono,fontSize:24,fontWeight:900}}>CHI</div></div><div style={{border:`1px solid ${C.ink}`,padding:14,textAlign:"center"}}><small>SERRATURA 02</small><div style={{fontFamily:mono,fontSize:24,fontWeight:900}}>COSA</div></div></div><Btn onClick={onOpen}>APRI IL FASCICOLO</Btn></div></section>}
export default function App(){const[fase,setFase]=useState("apertura"),[grid,setGrid]=useState(PUZ.map(r=>[...r])),[nome,setNome]=useState(""),[err,setErr]=useState(""),[q,setQ]=useState(0),[ipotesi,setIpotesi]=useState(""),[grattato,setGrattato]=useState(false),[scratchDone,setScratchDone]=useState(false),[doppio,setDoppio]=useState(false);
useEffect(()=>{if(!scratchDone||(fase!=="sicura"&&fase!=="insicura"))return;const t=setTimeout(()=>setFase("pacco"),10000);return()=>clearTimeout(t)},[scratchDone,fase]);
useEffect(()=>{if(fase!=="pacco")return;const t=setTimeout(()=>setDoppio(true),DOPPIO_FONDO.attesa);return()=>clearTimeout(t)},[fase]);
const setCell=(r,c,v)=>{if(PUZ[r][c])return;const n=v.replace(/[^1-9]/g,"").slice(-1),g=grid.map(x=>[...x]);g[r][c]=n?+n:0;setGrid(g)};
const sudokuOk=grid.every((r,i)=>r.every((v,j)=>v===SOL[i][j]));
const checkNome=()=>{if(nome.trim().toUpperCase()===NOME.soluzione){setErr("");setFase("nome-ok")}else setErr(NOME.errore)};
const answer=yes=>{setScratchDone(false);if(QUIZ[q].finale){setFase(yes?"sicura":"insicura");return}setQ(q+1)};
return <div style={{minHeight:"100vh",background:`radial-gradient(circle at top,#2b2a22,${C.dark} 58%,#090a08)`,color:C.ink,padding:"22px 14px 50px"}}><main style={{maxWidth:620,margin:"0 auto"}}>
{fase==="apertura"&&<Opening onOpen={()=>setFase("sudoku")}/>} 
{fase==="sudoku"&&<Card label="SERRATURA 01 · IN CORSO"><Stamp>PROVA 01</Stamp><Head eye={SUDOKU.occhiello} title={SUDOKU.titolo}/><Text>{SUDOKU.testo}</Text><div style={{display:"grid",gridTemplateColumns:"repeat(9,1fr)",border:`2px solid ${C.ink}`,marginBottom:18}}>{grid.flatMap((row,r)=>row.map((v,c)=><input key={`${r}-${c}`} value={v||""} readOnly={!!PUZ[r][c]} inputMode="numeric" onChange={e=>setCell(r,c,e.target.value)} style={{width:"100%",aspectRatio:"1",textAlign:"center",fontFamily:mono,fontSize:16,border:"0",borderRight:c%3===2&&c<8?`2px solid ${C.ink}`:`1px solid #aaa`,borderBottom:r%3===2&&r<8?`2px solid ${C.ink}`:`1px solid #aaa`,background:PUZ[r][c]?"rgba(24,37,31,.12)":"transparent",fontWeight:PUZ[r][c]?900:500}}/>))}</div><Btn disabled={!sudokuOk} onClick={()=>setFase("sudoku-ok")}>APRI IL PRIMO SIGILLO</Btn><TestBtn onClick={()=>setGrid(SOL.map(r=>[...r]))}>TEST · RISOLVI SUDOKU AUTOMATICAMENTE</TestBtn></Card>}
{fase==="sudoku-ok"&&<Card label="SERRATURA 01 · APERTA"><Stamp>INDIZIO RECUPERATO</Stamp><Head eye="PRIMO SIGILLO APERTO" title="Un dato è stato sbloccato"/><Text>{SUDOKU.vinta}</Text><Btn onClick={()=>setFase("nome")}>PASSA ALL'IDENTIFICAZIONE</Btn></Card>}
{fase==="nome"&&<Card label="IDENTIFICAZIONE MITTENTE"><Stamp>SERRATURA · CHI</Stamp><Head eye={NOME.occhiello} title={NOME.titolo}/><Text>{NOME.testo}</Text><input value={nome} onChange={e=>setNome(e.target.value)} placeholder="SEI LETTERE" style={{width:"100%",padding:16,border:`2px solid ${C.ink}`,background:"transparent",fontFamily:mono,fontSize:20,textTransform:"uppercase",marginBottom:10}}/>{err&&<p style={{color:C.rosso}}>{err}</p>}<Btn disabled={!nome.trim()} onClick={checkNome}>VERIFICA IL MITTENTE</Btn></Card>}
{fase==="nome-ok"&&<Card label="MITTENTE CONFERMATO"><Stamp>IDENTITÀ VERIFICATA</Stamp><Head eye="MITTENTE IDENTIFICATO" title={NOME.soluzione}/><Text>{NOME.vinta}</Text><Btn onClick={()=>setFase("quiz")}>APRI LA SERRATURA COSA</Btn></Card>}
{fase==="quiz"&&<Card label={`SERRATURA 02 · DOMANDA ${q+1}/${QUIZ.length}`}><Stamp>INTERROGATORIO</Stamp><Head eye={`DOMANDA ${q+1} / ${QUIZ.length}`} title={QUIZ[q].d}/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><Btn onClick={()=>answer(true)}>SÌ</Btn><Btn alt onClick={()=>answer(false)}>NO</Btn></div></Card>}
{fase==="sicura"&&<Card label="ULTIMO INDIZIO"><Stamp>IPOTESI RICHIESTA</Stamp><Head eye="SERRATURA 02" title={SICURA.testo}/>{!grattato?<><input value={ipotesi} onChange={e=>setIpotesi(e.target.value)} placeholder={SICURA.campo} style={{width:"100%",padding:16,border:`2px solid ${C.ink}`,background:"transparent",fontFamily:serif,fontSize:17,marginBottom:12}}/><Btn disabled={!ipotesi.trim()} onClick={()=>setGrattato(true)}>{SICURA.bottone}</Btn></>:<><Text>{SICURA.dopo} Ora gratti la patina.</Text><ScratchCard text={SICURA.gratta} image={ZIP_IMG} onDone={()=>setScratchDone(true)}/>{scratchDone&&<div style={{fontFamily:mono,textAlign:"center",fontSize:11,color:C.rosso,fontWeight:900}}>ASPETTA UN ATTIMO…</div>}</>}</Card>}
{fase==="insicura"&&<Card label="ULTIMO INDIZIO"><Stamp>AIUTO AUTORIZZATO</Stamp><Head eye="SERRATURA 02" title={INSICURA.testo}/><Text>{INSICURA.sottotesto} L'indizio è nascosto sotto la patina.</Text><ScratchCard text={INSICURA.gratta} image={ZIP_IMG} onDone={()=>setScratchDone(true)}/>{scratchDone&&<div style={{fontFamily:mono,textAlign:"center",fontSize:11,color:C.rosso,fontWeight:900}}>ASPETTA UN ATTIMO…</div>}</Card>}
{fase==="pacco"&&<><section style={{background:C.ink,color:C.chiara,padding:"42px 22px",textAlign:"center",marginBottom:18,border:`1px solid ${C.oro}`}}><Stamp>FALSO FINALE</Stamp><h1 style={{fontFamily:serif,fontSize:34,margin:"0 0 18px"}}>{PACCO.titolo}</h1><p style={{fontFamily:serif,fontSize:25,whiteSpace:"pre-line",color:C.oro}}>{PACCO.regalo}</p></section>{doppio&&<section style={{background:C.oro,padding:"32px 22px",textAlign:"center"}}><Stamp>DOPPIO FONDO</Stamp><h2 style={{fontFamily:serif,fontSize:28}}>{DOPPIO_FONDO.titolo}</h2><Text>{DOPPIO_FONDO.testo}</Text><a href={DOPPIO_FONDO.link} target="_blank" rel="noreferrer" style={{display:"block",background:C.ink,color:C.chiara,padding:16,textDecoration:"none",fontFamily:mono,fontWeight:900,letterSpacing:2}}>{DOPPIO_FONDO.bottone}</a><p style={{fontFamily:serif,fontStyle:"italic"}}>{DOPPIO_FONDO.chiusura}</p></section>}</>}
<div style={{fontFamily:mono,fontSize:10,letterSpacing:2,textAlign:"center",color:C.carta,opacity:.55,marginTop:28}}>UFFICIO CASI IRRISOLTI · FASCICOLO 08/26</div></main></div>}
