import React,{useEffect,useState} from "react";
import {APERTURA,SUDOKU,NOME,QUIZ,SICURA,INSICURA,GRATTA,PACCO,DOPPIO_FONDO,SOL,PUZ} from "./dati.js";
const C={carta:"#d8c18d",chiara:"#f1e4bc",ink:"#171813",rosso:"#8b271f",oro:"#b58b3b",tenue:"#6f6756",dark:"#11120f"};
const mono="ui-monospace,SFMono-Regular,Menlo,monospace",serif="Georgia,serif";
function Btn({children,onClick,disabled=false,alt=false}){return <button disabled={disabled} onClick={onClick} style={{width:"100%",padding:"16px 18px",border:`1px solid ${alt?C.oro:C.ink}`,background:alt?"transparent":C.ink,color:alt?C.ink:C.chiara,fontFamily:mono,fontWeight:900,letterSpacing:2,cursor:"pointer",opacity:disabled?.45:1,textTransform:"uppercase"}}>{children}</button>}
function Card({children}){return <section style={{background:C.chiara,border:`1px solid rgba(23,24,19,.75)`,padding:22,boxShadow:"0 18px 45px rgba(0,0,0,.18)",marginBottom:22}}>{children}</section>}
function Head({eye,title}){return <><div style={{fontFamily:mono,fontSize:11,letterSpacing:2,color:C.rosso,fontWeight:900}}>{eye}</div><h1 style={{fontFamily:serif,fontSize:30,lineHeight:1.05,whiteSpace:"pre-line",margin:"10px 0 18px"}}>{title}</h1></>}
function Text({children}){return <div style={{fontFamily:serif,fontSize:17,lineHeight:1.55,whiteSpace:"pre-line",marginBottom:20}}>{children}</div>}
function Opening({onOpen}){return <section className="casefile" style={{position:"relative",overflow:"hidden",background:"linear-gradient(135deg,#ead9a8 0%,#cfb476 100%)",border:"1px solid #5f5132",boxShadow:"0 24px 70px rgba(0,0,0,.35)"}}>
  <div style={{padding:"14px 18px",borderBottom:"1px solid rgba(23,24,19,.45)",display:"flex",justifyContent:"space-between",gap:10,fontFamily:mono,fontWeight:900,fontSize:11,letterSpacing:1.4}}><span>FASCICOLO 08/26</span><span style={{color:C.rosso}}>CONSEGNA RISERVATA</span></div>
  <div style={{padding:"24px 22px 20px",position:"relative"}}>
    <div style={{position:"absolute",right:18,top:18,border:`3px solid ${C.rosso}`,color:C.rosso,fontFamily:mono,fontWeight:900,padding:"7px 10px",transform:"rotate(7deg)",letterSpacing:2,fontSize:12,opacity:.9}}>RISERVATO</div>
    <div style={{fontFamily:mono,fontSize:10,letterSpacing:2,color:C.tenue,marginBottom:18}}>DESTINATARIA UNICA · ACCESSO AUTORIZZATO</div>
    <h1 style={{fontFamily:serif,fontSize:"clamp(42px,11vw,68px)",lineHeight:.93,margin:"0 0 18px",maxWidth:520}}>C'È UN<br/><span style={{color:C.rosso}}>REGALO</span><br/>PER LEI.</h1>
    <p style={{fontFamily:serif,fontSize:19,lineHeight:1.5,maxWidth:500,margin:"0 0 22px"}}>Non è pubblicità. Non è uno scherzo. È una consegna personale, preparata apposta per lei.</p>
    <div style={{background:"rgba(255,248,220,.55)",border:"1px solid rgba(23,24,19,.45)",padding:16,marginBottom:18,display:"grid",gridTemplateColumns:"1fr auto",gap:14,alignItems:"center"}}><div><div style={{fontFamily:mono,fontSize:10,letterSpacing:1.5,color:C.tenue}}>STATO DEL PACCO</div><div style={{fontFamily:mono,fontWeight:900,fontSize:17,marginTop:5}}>SIGILLATO · CONTENUTO SCONOSCIUTO</div></div><div style={{fontSize:34}}>🎁</div></div>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginBottom:22}}><div style={{border:`1px solid ${C.ink}`,padding:14,textAlign:"center",background:"rgba(255,255,255,.16)"}}><div style={{fontFamily:mono,fontSize:9,letterSpacing:1.4,color:C.tenue}}>SERRATURA 01</div><div style={{fontFamily:mono,fontSize:24,fontWeight:900,marginTop:5}}>CHI</div><div style={{fontFamily:serif,fontSize:13,marginTop:4}}>Scopra il mittente</div></div><div style={{border:`1px solid ${C.ink}`,padding:14,textAlign:"center",background:"rgba(255,255,255,.16)"}}><div style={{fontFamily:mono,fontSize:9,letterSpacing:1.4,color:C.tenue}}>SERRATURA 02</div><div style={{fontFamily:mono,fontSize:24,fontWeight:900,marginTop:5}}>COSA</div><div style={{fontFamily:serif,fontSize:13,marginTop:4}}>Scopra il contenuto</div></div></div>
    <div style={{borderTop:"1px dashed rgba(23,24,19,.55)",paddingTop:18}}><div style={{fontFamily:mono,fontSize:11,letterSpacing:1.2,color:C.rosso,fontWeight:900,marginBottom:9}}>ISTRUZIONI DI APERTURA</div><p style={{fontFamily:serif,fontSize:16,lineHeight:1.55,margin:"0 0 18px"}}>Due serrature. Due risposte. Qualche indizio. Niente di impossibile. Il regalo vero è alla fine.</p><Btn onClick={onOpen}>APRI IL FASCICOLO</Btn></div>
  </div>
  <div style={{padding:"12px 18px",background:C.dark,color:C.carta,fontFamily:mono,fontSize:9,letterSpacing:1.6,textAlign:"center"}}>UFFICIO CASI IRRISOLTI · PRATICA ATTIVA</div>
</section>}
export default function App(){const[fase,setFase]=useState("apertura"),[grid,setGrid]=useState(PUZ.map(r=>[...r])),[nome,setNome]=useState(""),[err,setErr]=useState(""),[q,setQ]=useState(0),[ipotesi,setIpotesi]=useState(""),[grattato,setGrattato]=useState(false),[doppio,setDoppio]=useState(false);
useEffect(()=>{if(fase!=="pacco")return;const t=setTimeout(()=>setDoppio(true),DOPPIO_FONDO.attesa);return()=>clearTimeout(t)},[fase]);
const setCell=(r,c,v)=>{if(PUZ[r][c])return;const n=v.replace(/[^1-9]/g,"").slice(-1);const g=grid.map(x=>[...x]);g[r][c]=n?+n:0;setGrid(g)};
const sudokuOk=grid.every((r,i)=>r.every((v,j)=>v===SOL[i][j]));
const checkNome=()=>{if(nome.trim().toUpperCase()===NOME.soluzione){setErr("");setFase("nome-ok")}else setErr(NOME.errore)};
const answer=(yes)=>{if(QUIZ[q].finale){setFase(yes?"sicura":"insicura");return}setQ(q+1)};
return <div style={{minHeight:"100vh",background:`radial-gradient(circle at top,#2b2a22 0%,${C.dark} 58%,#090a08 100%)`,color:C.ink,padding:"22px 14px 50px",boxSizing:"border-box"}}><style>{`*{box-sizing:border-box}body{margin:0}.in{animation:in .35s ease}@keyframes in{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}input:focus{outline:2px solid ${C.oro}}@media(max-width:420px){.casefile{border-radius:0}}`}</style><main className="in" style={{maxWidth:620,margin:"0 auto"}}>{fase!=="apertura"&&<div style={{fontFamily:mono,fontSize:10,letterSpacing:3,textAlign:"center",marginBottom:18,color:C.carta}}>FASCICOLO 08/26 · RISERVATO</div>}
{fase==="apertura"&&<Opening onOpen={()=>setFase("sudoku")}/>} 
{fase==="sudoku"&&<Card><Head eye={SUDOKU.occhiello} title={SUDOKU.titolo}/><Text>{SUDOKU.testo}</Text><div style={{display:"grid",gridTemplateColumns:"repeat(9,1fr)",border:`2px solid ${C.ink}`,marginBottom:18}}>{grid.flatMap((row,r)=>row.map((v,c)=><input key={`${r}-${c}`} value={v||""} readOnly={!!PUZ[r][c]} inputMode="numeric" onChange={e=>setCell(r,c,e.target.value)} style={{width:"100%",aspectRatio:"1",textAlign:"center",fontFamily:mono,fontSize:16,border:"0",borderRight:c%3===2&&c<8?`2px solid ${C.ink}`:`1px solid rgba(24,37,31,.3)`,borderBottom:r%3===2&&r<8?`2px solid ${C.ink}`:`1px solid rgba(24,37,31,.3)`,background:PUZ[r][c]?"rgba(24,37,31,.1)":"transparent"}}/>))}</div><Btn disabled={!sudokuOk} onClick={()=>setFase("sudoku-ok")}>APRI IL PRIMO SIGILLO</Btn></Card>}
{fase==="sudoku-ok"&&<Card><Head eye="INDIZIO RECUPERATO" title="Primo sigillo aperto"/><Text>{SUDOKU.vinta}</Text><Btn onClick={()=>setFase("nome")}>CONTINUA</Btn></Card>}
{fase==="nome"&&<Card><Head eye={NOME.occhiello} title={NOME.titolo}/><Text>{NOME.testo}</Text><input value={nome} onChange={e=>setNome(e.target.value)} onKeyDown={e=>e.key==="Enter"&&checkNome()} placeholder="SEI LETTERE" style={{width:"100%",padding:15,border:`2px solid ${C.ink}`,background:"transparent",fontFamily:mono,fontSize:18,textTransform:"uppercase",marginBottom:10}}/>{err&&<p style={{color:C.rosso,fontFamily:serif}}>{err}</p>}<Btn disabled={!nome.trim()} onClick={checkNome}>VERIFICA IL MITTENTE</Btn></Card>}
{fase==="nome-ok"&&<Card><Head eye="MITTENTE IDENTIFICATO" title={NOME.soluzione}/><Text>{NOME.vinta}</Text><Btn onClick={()=>setFase("quiz")}>SCOPRI COS'È</Btn></Card>}
{fase==="quiz"&&<Card><Head eye={`DOMANDA ${q+1} / ${QUIZ.length}`} title={QUIZ[q].d}/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><Btn onClick={()=>answer(true)}>SÌ</Btn><Btn alt onClick={()=>answer(false)}>NO</Btn></div></Card>}
{fase==="sicura"&&<Card><Head eye="ULTIMO INDIZIO" title={SICURA.testo}/>{!grattato?<><input value={ipotesi} onChange={e=>setIpotesi(e.target.value)} placeholder={SICURA.campo} style={{width:"100%",padding:15,border:`2px solid ${C.ink}`,background:"transparent",fontFamily:serif,fontSize:17,marginBottom:12}}/><Btn disabled={!ipotesi.trim()} onClick={()=>setGrattato(true)}>{SICURA.bottone}</Btn></>:<><Text>{SICURA.dopo}</Text><div style={{padding:28,textAlign:"center",background:C.oro,fontFamily:mono,fontWeight:900,fontSize:22,whiteSpace:"pre-line",marginBottom:16}}>{SICURA.gratta}</div><Btn onClick={()=>setFase("pacco")}>{GRATTA.bottone}</Btn></>}</Card>}
{fase==="insicura"&&<Card><Head eye="ULTIMO INDIZIO" title={INSICURA.testo}/><Text>{INSICURA.sottotesto}</Text><div style={{padding:28,textAlign:"center",background:C.oro,fontFamily:mono,fontWeight:900,fontSize:22,whiteSpace:"pre-line",marginBottom:16}}>{INSICURA.gratta}</div><Btn onClick={()=>setFase("pacco")}>{GRATTA.bottone}</Btn></Card>}
{fase==="pacco"&&<><section style={{background:C.ink,color:C.chiara,padding:"38px 22px",textAlign:"center",marginBottom:18}}><div style={{fontFamily:mono,color:C.oro,fontWeight:900,letterSpacing:3}}>CASO RISOLTO</div><h1 style={{fontFamily:mono,textTransform:"uppercase",fontSize:23}}>{PACCO.titolo}</h1><div style={{fontFamily:mono,fontSize:10,letterSpacing:4,color:C.carta}}>{PACCO.occhiello}</div><p style={{fontFamily:serif,fontSize:30,whiteSpace:"pre-line"}}>{PACCO.regalo}</p></section>{doppio&&<section className="in" style={{background:C.oro,padding:"30px 22px",textAlign:"center"}}><h2 style={{fontFamily:mono,textTransform:"uppercase"}}>{DOPPIO_FONDO.titolo}</h2><Text>{DOPPIO_FONDO.testo}</Text><a href={DOPPIO_FONDO.link} target="_blank" rel="noreferrer" style={{display:"block",background:C.ink,color:C.chiara,padding:16,textDecoration:"none",fontFamily:mono,fontWeight:900,letterSpacing:2}}>{DOPPIO_FONDO.bottone}</a><p style={{fontFamily:serif,fontStyle:"italic"}}>{DOPPIO_FONDO.chiusura}</p></section>}</>}
{fase!=="apertura"&&<div style={{fontFamily:mono,fontSize:10,letterSpacing:2,textAlign:"center",color:C.carta,opacity:.65,marginTop:28}}>UFFICIO CASI IRRISOLTI</div>}</main></div>}
