export const MESSAGGI = [
  "Amo scusa il ritardo", "ma è successa una cosa assurda",
  "mentre uscivo mi ha fermata uno e mi ha dato una busta per te",
  "ha detto solo \"dille che deve aprirla lei, e che io non c'entro niente\" e se n'è andato",
  "io sono rimasta imbambolata giuro", "comunque dentro c'era scritto solo questo 👇",
  "[QUI IL LINK]", "non chiedermi altro perché non so niente 😭",
];
export const APERTURA={occhiello:"FASCICOLO RISERVATO · DESTINATARIA UNICA",titolo:"È arrivato qualcosa\nper lei",testo:`Se sta leggendo questa pagina, il pacco è già stato consegnato nel modo previsto.\n\nLa persona che le ha inviato il link non è il mittente. È soltanto il tramite e, cosa piuttosto rara, questa volta non sa davvero niente.\n\nDa questo momento le informazioni ufficiali sono tre:\n\n— esiste un pacco;\n— è intestato a lei;\n— nessuno ha intenzione di dirle cosa contiene.\n\nSul mittente il fascicolo riporta soltanto qualche dettaglio: poteva scriverle direttamente e ha deciso di non farlo; ha preferito costruire tutto questo invece di limitarsi a dire \"ti ho preso un regalo\"; e ci ha dedicato decisamente più tempo del necessario.\n\nIl pacco è protetto da due serrature.\n\nLa prima domanda è CHI.\nLa seconda è COSA.\n\nLe apra entrambe e il contenuto sarà suo.`,bottone:"APRI IL FASCICOLO"};
export const SUDOKU={occhiello:"PRIMO SIGILLO",titolo:"La griglia",testo:`Per ottenere il primo indizio deve superare una piccola prova. Niente di impossibile: solo un Sudoku per scaldare un po' le indagini.\n\nCompleti la griglia inserendo i numeri da 1 a 9: ogni numero deve comparire una sola volta in ogni riga, in ogni colonna e in ogni riquadro 3×3.\n\nQuando il Sudoku sarà corretto, il primo sigillo si aprirà e comparirà il primo indizio sul mittente.`,vinta:`PRIMO INDIZIO RECUPERATO.\n\nIl Sudoku è risolto e il primo sigillo è aperto.\n\nEcco il primo indizio:\n\nIL NOME DEL MITTENTE È COMPOSTO DA SEI LETTERE.\n\nOra può provare ad aprire la serratura CHI.`};
export const NOME={occhiello:"SECONDO SIGILLO",titolo:"Chi ha mandato il pacco",testo:"Sei lettere. Se lo conosce davvero, non le serve altro.",soluzione:"SIMONE",errore:"Non è lui. Ci pensi ancora un attimo.",vinta:`Identificato.\n\nIl sospettato conferma tutto e aggiunge una cosa sola, che gli sembrava importante dire: scegliere è stato difficilissimo.\n\nLe opzioni erano tante, alcune anche discretamente stupide, e per giorni non è riuscito a decidersi. Alla fine ne ha scelta una, ed è convinto di averci preso.\n\nAdesso viene il bello: capire cos'è. Risponda a queste domande e vediamo se ci arriva.`};
export const QUIZ=[{d:"Il regalo entra in una borsa?"},{d:"È una cosa che si fa, più che una cosa che si tiene?"},{d:"Ti toccherà spegnere il telefono per un po'?"},{d:"Servirà una giornata libera, non mezz'ora?"},{d:"Ritieni di aver capito il regalo?",finale:true}];
export const SICURA={testo:"Bene! Scrivilo e lo scoprirai",campo:"Scrivi qui cosa pensi che sia…",bottone:"È LA MIA RISPOSTA",dopo:"Vediamo se ci ha preso.",gratta:"ZIPLINE\nla più lunga d'Europa"};
export const INSICURA={testo:"Ma come, pensavo fosse così semplice!",sottotesto:"Dai ti do un indizio…",gratta:"ZIPLINE\nla più lunga d'Europa"};
export const GRATTA={invito:"Gratta con il dito",bottone:"VAI AVANTI"};
export const PACCO={occhiello:"E DENTRO C'È",titolo:"Hai trovato il pacco misterioso!",regalo:"Un buono per la zipline\npiù lunga d'Europa"};
export const DOPPIO_FONDO={attesa:10000,titolo:"Aspetta, c'è un doppio fondo…",testo:"C'è anche questo.",bottone:"APRI IL SECONDO REGALO",link:"https://voucher.qcterme.com/api/voucher/5833e680-e9d3-4972-885c-951fdfb229f3/041b8f58-894e-4585-8a66-2c54b7bacefb",chiusura:"Caso chiuso. Il colpevole si dichiara colpevole."};
export const SOL=[[2,4,9,3,6,8,7,1,5],[3,5,6,9,7,1,8,2,4],[7,8,1,5,4,2,6,3,9],[5,1,2,7,8,3,4,9,6],[8,7,4,6,2,9,1,5,3],[6,9,3,1,5,4,2,7,8],[9,6,7,4,1,5,3,8,2],[4,2,5,8,3,7,9,6,1],[1,3,8,2,9,6,5,4,7]];
export const PUZ=[[0,0,0,0,0,8,0,0,5],[3,0,6,9,0,0,8,0,0],[0,0,1,5,0,0,0,0,9],[5,1,0,7,0,3,4,0,6],[8,0,4,0,0,0,1,0,0],[0,0,0,1,0,4,2,0,0],[0,6,7,4,1,0,0,8,0],[4,2,5,0,0,0,0,0,1],[1,0,0,0,0,6,0,0,0]];
